- hosts: nginx
  remote_user: "{{ REMOTE_USER_ADMIN }}"
  roles:
  - main
  tasks:
   - name: kill nginx port
     shell: ps -ef|grep nginx|grep "master process"|grep -v grep|awk -F " " '{print $2}'|xargs -r kill
   - name: mkdir nginx path
     shell: "mkdir -p {{ REMOTE_PREFIX_PATH }}software/workspace/nginx/ && mkdir -p {{ REMOTE_PREFIX_PATH }}software/install/nginx_workspace/ && rm -rf {{ REMOTE_PREFIX_PATH }}software/workspace/nginx/* && rm -rf {{ REMOTE_PREFIX_PATH }}software/install/nginx_workspace/*"
   - name: cp nginx
     copy:
      src: "{{ LOCAL_FILES_PATH }}software/workspace/nginx/nginx-1.10.2.tar.gz"
      dest: "{{ REMOTE_PREFIX_PATH }}software/workspace/nginx/"
   - name: cp nginx_workspace
     copy:
      src: "{{ LOCAL_FILES_PATH }}software/workspace/nginx/nginx_workspace_v1.10.2.tar.gz"
      dest: "{{ REMOTE_PREFIX_PATH }}software/install/nginx_workspace/"
   - name: unzip nginx
     shell: "cd {{ REMOTE_PREFIX_PATH }}software/workspace/nginx/ && tar -zxf nginx-1.10.2.tar.gz"
   - name: unzip nginx_workspace
     shell: "cd {{ REMOTE_PREFIX_PATH }}software/install/ && tar -zxf nginx_workspace/nginx_workspace_v1.10.2.tar.gz -C {{ REMOTE_PREFIX_PATH }}software/install/ && rm -f nginx_workspace/nginx_workspace_v1.10.2.tar.gz"
   - name: chown nginx
     shell: "chown -R {{ REMOTE_USER_ADMIN }}.{{ REMOTE_USER_ADMIN }} {{ REMOTE_PREFIX_PATH }}software/workspace/nginx/"
   - name: chown nginx
     shell: "chown -R {{ REMOTE_USER_ADMIN }}.{{ REMOTE_USER_ADMIN }} {{ REMOTE_PREFIX_PATH }}software/install/nginx_workspace/"
   - name: ln -s nginx
     shell: "rm -f {{ REMOTE_PREFIX_PATH }}software/install/nginx && ln -s {{ REMOTE_PREFIX_PATH }}software/install/nginx_workspace/ {{ REMOTE_PREFIX_PATH }}software/install/nginx"
   - name: ln -s nginx command
     shell: "rm -f /usr/bin/nginx && ln -s {{ REMOTE_PREFIX_PATH }}software/install/nginx/sbin/nginx /usr/bin/nginx"
   - name: start nginx
     shell: nginx -v && nginx -t && nginx
