- hosts: elasticjob
  remote_user: "{{ REMOTE_USER_ADMIN }}"
  roles:
  - main 
  tasks:
   - name: kill elasticjob port
     shell: ps -ef|grep "8899"|grep -v grep|awk -F " " '{print $2}'|xargs -r kill
   - name: mkdir rm elastic-job-lite-console
     shell: "mkdir -p {{ REMOTE_PREFIX_PATH }}software/workspace/elastic-job-lite-console/ && rm -rf {{ REMOTE_PREFIX_PATH }}software/workspace/elastic-job-lite-console/*"
   - name: cp elasticjob
     copy:
      src: "{{ LOCAL_FILES_PATH }}software/workspace/elastic-job-lite-console/elastic-job-lite-console-2.1.5.tar.gz"
      dest: "{{ REMOTE_PREFIX_PATH }}software/workspace/elastic-job-lite-console/"
   - name: unzip elasticjob
     shell: "cd {{ REMOTE_PREFIX_PATH }}software/workspace/elastic-job-lite-console/ && tar -zxf elastic-job-lite-console-2.1.5.tar.gz"
   - name: chown elasticjob
     shell: "chown -R {{ REMOTE_USER_ADMIN }}.{{ REMOTE_USER_ADMIN }} {{ REMOTE_PREFIX_PATH }}software/workspace/elastic-job-lite-console/"
   - name: ln -s elasticjob
     shell: "rm -f {{ REMOTE_PREFIX_PATH }}software/install/elastic-job-lite-console && ln -s {{ REMOTE_PREFIX_PATH }}software/workspace/elastic-job-lite-console/elastic-job-lite-console-2.1.5 {{ REMOTE_PREFIX_PATH }}software/install/elastic-job-lite-console"
   - name: start elasticjob
     shell: "cd {{ REMOTE_PREFIX_PATH }}software/install/elastic-job-lite-console && /usr/bin/nohup /bin/sh bin/start.sh > /dev/null 2>&1 &"

