- hosts: node
  remote_user: "{{ REMOTE_USER_ADMIN }}"
  roles:
  - main
  tasks:
   - name: mkdir node path
     shell: "mkdir -p {{ REMOTE_PREFIX_PATH }}software/workspace/node/ && mkdir -p {{ REMOTE_PREFIX_PATH }}software/install/node_workspace/ && rm -rf {{ REMOTE_PREFIX_PATH }}software/workspace/node/* && rm -rf {{ REMOTE_PREFIX_PATH }}software/install/node_workspace/*"
   - name: cp node
     copy:
      src: "{{ LOCAL_FILES_PATH }}software/workspace/node/node-v6.14.2.tar.gz"
      dest: "{{ REMOTE_PREFIX_PATH }}software/workspace/node/"
   - name: cp node_workspace
     copy:
      src: "{{ LOCAL_FILES_PATH }}software/workspace/node/node_workspace-v6.14.2.tar.gz"
      dest: "{{ REMOTE_PREFIX_PATH }}software/install/node_workspace/"
   - name: unzip node
     shell: "cd {{ REMOTE_PREFIX_PATH }}software/workspace/node/ && tar -zxf node-v6.14.2.tar.gz"
   - name: unzip node_workspace
     shell: "cd {{ REMOTE_PREFIX_PATH }}software/install/ && tar -zxf node_workspace/node_workspace-v6.14.2.tar.gz -C {{ REMOTE_PREFIX_PATH }}software/install/ && rm -f node_workspace/node_workspace-v6.14.2.tar.gz"
   - name: chown node
     shell: "chown -R {{ REMOTE_USER_ADMIN }}.{{ REMOTE_USER_ADMIN }} {{ REMOTE_PREFIX_PATH }}software/workspace/node/"
   - name: chown node_workspace
     shell: "chown -R {{ REMOTE_USER_ADMIN }}.{{ REMOTE_USER_ADMIN }} /data/software/install/node_workspace/"
   - name: ln -s node
     shell: "rm -f {{ REMOTE_PREFIX_PATH }}software/install/node && ln -s {{ REMOTE_PREFIX_PATH }}software/install/node_workspace/ {{ REMOTE_PREFIX_PATH }}software/install/node"
   - name: ln -s node command
     shell: "rm -f /usr/bin/node && ln -s {{ REMOTE_PREFIX_PATH }}software/install/node/bin/node /usr/bin/node"
   - name: ln -s npm command
     shell: "rm -f /usr/bin/npm && ln -s {{ REMOTE_PREFIX_PATH }}software/install/node/bin/npm /usr/bin/npm"
   - name: test node npm
     shell: node -v && npm -v

