
#!/usr/bin/expect
if { $argc != 4 } {
        send_user "usage: expect expect.exp file host \n"
        exit
}
#define var
set file [lindex $argv 0]
set host [lindex $argv 1]
set username [lindex $argv 2]
set password [lindex $argv 3]
#exec command
spawn ssh-copy-id -i $file "-p 22 $username@$host"
expect {
        "yes/no"        {send "yes\r";exp_continue}
        "*password"     {send  "$password\r"}
}
expect eof

