- hosts: allhosts
  remote_user: "{{ REMOTE_USER_ADMIN }}"
  roles: 
  - main 
  tasks:
   - name: rm ln -s jdk
     shell: "rm -f {{ REMOTE_PREFIX_PATH }}software/install/jdk"
   - name: rm ln -s java
     shell: rm -f /usr/bin/java
   - name: rm ln -s javac
     shell: rm -f /usr/bin/javac
   - name: rm ln -s jar
     shell: rm -f /usr/bin/jar
   - name: del jdk
     shell: "rm -rf {{ REMOTE_PREFIX_PATH }}software/workspace/jdk/"


