- hosts: apollo-config-pro-01 
  remote_user: "{{ REMOTE_USER_ADMIN }}" 
  roles:
  - main
  tasks:
   - name: kill apollo-portal port
     shell: ps -ef|grep "server.port=8070"|grep -v grep|awk -F " " '{print $2}'|xargs -r kill
   - name: kill apollo-admin port
     shell: ps -ef|grep "server.port=8090"|grep -v grep|awk -F " " '{print $2}'|xargs -r kill
   - name: kill apollo-config port
     shell: ps -ef|grep "server.port=8080"|grep -v grep|awk -F " " '{print $2}'|xargs -r kill
   - name: rm apollo
     shell: "rm -rf {{ REMOTE_PREFIX_PATH }}application/{project,logs}/apollo/"

