- hosts: allhosts
  remote_user: "{{ REMOTE_USER_ADMIN }}"
  roles: 
  - main
  tasks:
   - name: cp all system sh     
     copy:      
      src: "{{ LOCAL_FILES_PATH }}scripts/system/"
      dest: "{{ REMOTE_PREFIX_PATH }}backup/scripts/system/"
   - name: chmod +x all system sh
     shell: "chmod +x {{ REMOTE_PREFIX_PATH }}backup/scripts/system/*"
   - name: sh restore-system.sh
     shell: "/bin/sh {{ REMOTE_PREFIX_PATH }}backup/scripts/system/restore-system.sh {{ REMOTE_PREFIX_PATH }}"
     ignore_errors: yes
