- hosts: node
  remote_user: "{{ REMOTE_USER_ADMIN }}" 
  roles:
  - main
  tasks:
   - name: rm ln -s node
     shell: "rm -f {{ REMOTE_PREFIX_PATH }}software/install/node"
   - name: rm ln -s node command
     shell: rm -f /usr/bin/node
   - name: rm ln -s npm command
     shell: rm -f /usr/bin/npm
   - name: rm node path
     shell: "rm -rf {{ REMOTE_PREFIX_PATH }}software/workspace/node/ && rm -rf {{ REMOTE_PREFIX_PATH }}software/install/node_workspace/"

