- hosts: zookeeper
  remote_user: "{{ REMOTE_USER_ADMIN }}"
  roles:
  - main
  tasks:
   - name: kill zookeeper port
     shell: ps -ef|grep "zookeeper"|grep -v grep|awk -F " " '{print $2}'|xargs -r kill
   - name: rm ln -s zookeeper
     shell: "rm -f {{ REMOTE_PREFIX_PATH }}software/install/zookeeper && rm -rf {{ REMOTE_PREFIX_PATH }}software/workspace/zookeeper/"
