- hosts: elasticjob
  remote_user: "{{ REMOTE_USER_ADMIN }}"
  roles:
  - main
  tasks:
   - name: kill elasticjob port
     shell: ps -ef|grep "8899"|grep -v grep|awk -F " " '{print $2}'|xargs -r kill
   - name: rm elastic-job-lite-console
     shell: "rm -f {{ REMOTE_PREFIX_PATH }}software/install/elastic-job-lite-console && rm -rf {{ REMOTE_PREFIX_PATH }}software/workspace/elastic-job-lite-console/"

