- hosts: eureka
  remote_user: "{{ REMOTE_USER_ADMIN }}"
  roles:
  - main
  tasks:
   - name: kill eureka port
     shell: ps -ef|grep "server.port=9000"|grep -v grep|awk -F " " '{print $2}'|xargs -r kill
   - name: rm eureka-server
     shell: "rm -rf {{ REMOTE_PREFIX_PATH }}application/{project,logs}/eureka-server/"

